# ~/.tmux.conf

# Essentials
set -sg escape-time 0
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g focus-events on
set -g status-position top
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Prefix
set-option -g prefix C-Space

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Windows
bind t new-window
bind h previous-window
bind l next-window
bind w kill-pane
